/**
 * NailSnap AI - Preset Library
 * Bộ sưu tập mẫu móng thịnh hành tại Việt Nam & Hoa Kỳ
 */

const NAIL_PRESETS = [
    {
        id: "douyin-blush-jelly",
        name: "Thạch Hồng Đào Douyin",
        category: "douyin",
        categoryName: "🌸 Douyin & Hàn Quốc",
        shape: "almond",
        length: 1.25,
        finish: "jelly",
        primaryColor: "#FF8DA1",
        secondaryColor: "#FFF0F5",
        frenchTip: false,
        gemstones: false,
        glitter: true,
        catEye: false,
        tag: "Hot Trend 2026",
        description: "Lớp sơn thạch trong veo ửng hồng ở tâm móng, viền bóng gương chuẩn nàng thơ Bắc Kinh/Seoul.",
        recipe: "Sơn lót Jelly Nude 2 lớp + Tán cọ ombré hồng đào tâm móng + Top bóng thủy tinh không trầy"
    },
    {
        id: "cat-eye-moonlight",
        name: "Mắt Mèo Ánh Trăng Khuyết",
        category: "douyin",
        categoryName: "🌸 Douyin & Hàn Quốc",
        shape: "almond",
        length: 1.3,
        finish: "cat_eye",
        primaryColor: "#2C3E50",
        secondaryColor: "#BDC3C7",
        frenchTip: false,
        gemstones: true,
        glitter: true,
        catEye: true,
        tag: "Triệu View TikTok",
        description: "Bột nhũ mắt mèo nam châm hút vầng sáng 3D huyền ảo, lấp lánh theo cử động ngón tay.",
        recipe: "Nền thạch đen khói + Hút nam châm tạo quầng trăng bạc 3D + Đính charm đá giọt nước"
    },
    {
        id: "korean-syrup-peach",
        name: "Siro Đào Phai Hàn Quốc",
        category: "douyin",
        categoryName: "🌸 Douyin & Hàn Quốc",
        shape: "round",
        length: 1.15,
        finish: "jelly",
        primaryColor: "#FFB085",
        secondaryColor: "#FFF7ED",
        frenchTip: false,
        gemstones: false,
        glitter: false,
        catEye: false,
        tag: "Nhẹ Nhàng Tự Nhiên",
        description: "Sắc cam đào mọng nước như giọt siro tan chảy, cực kỳ tôn da và hợp đi học/đi làm.",
        recipe: "Sơn thạch syrup cam đào 3 lớp mỏng + Top coat gel bóng nước"
    },
    {
        id: "hanoi-emerald-royal",
        name: "Cẩm Thạch Lục Bảo Hoàng Gia",
        category: "luxury",
        categoryName: "💎 Sang Chảnh & Quý Phái (Hà Nội)",
        shape: "coffin",
        length: 1.4,
        finish: "glossy",
        primaryColor: "#0D5C3A",
        secondaryColor: "#2ECC71",
        frenchTip: false,
        gemstones: true,
        glitter: true,
        catEye: false,
        goldFoil: true,
        tag: "Hợp Mệnh Thủy/Mộc",
        description: "Vân đá cẩm thạch xanh ngọc bích phối lá vàng 24k dát mỏng, đính pha lê Swarovski kiêu kỳ.",
        recipe: "Vẽ vân đá loang cẩm thạch ngọc bích + Dát vàng lá 24k + Đính cụm đá pha lê chân móng"
    },
    {
        id: "bordeaux-velvet-queen",
        name: "Đỏ Rượu Vang Bordeaux Nữ Quyền",
        category: "luxury",
        categoryName: "💎 Sang Chảnh & Quý Phái (Hà Nội)",
        shape: "square",
        length: 1.25,
        finish: "glossy",
        primaryColor: "#6B0D1B",
        secondaryColor: "#3E050D",
        frenchTip: false,
        gemstones: true,
        glitter: false,
        catEye: false,
        tag: "Tôn Trắng Mọi Da",
        description: "Sắc đỏ rượu vang đậm đà quyền lực, tôn trắng mọi tone da ngăm hay sáng, điểm xuyết viền đá chân móng.",
        recipe: "Sơn gel đỏ rượu vang Bordeaux 2 lớp đậm + Viền bi bạc và đá chân ngón trỏ"
    },
    {
        id: "wedding-pearl-bridal",
        name: "Bạch Ngọc Trai Nàng Dâu",
        category: "luxury",
        categoryName: "💎 Sang Chảnh & Quý Phái (Hà Nội)",
        shape: "almond",
        length: 1.35,
        finish: "glossy",
        primaryColor: "#FFF9F5",
        secondaryColor: "#F4E0D9",
        frenchTip: true,
        frenchColor: "#E8C39E",
        gemstones: true,
        glitter: true,
        catEye: false,
        tag: "Nail Cô Dâu Đẹp Nhất",
        description: "Nền trắng sữa ngọc trai ánh xà cừ, đính hoa nổi 3D và ngọc trai thanh khiết cho ngày cưới.",
        recipe: "Tráng gương bột ngọc trai White Chrome + Đắp hoa nổi 3D ngón nhẫn + Đính hạt trai"
    },
    {
        id: "saigon-cyber-chrome",
        name: "Tráng Gương Bạc Y2K Cyberpunk",
        category: "y2k",
        categoryName: "⚡ Y2K & Cháy Phố (Sài Gòn & USA)",
        shape: "stiletto",
        length: 1.5,
        finish: "chrome",
        primaryColor: "#D1D5DB",
        secondaryColor: "#111827",
        frenchTip: false,
        gemstones: false,
        glitter: false,
        catEye: false,
        tag: "Hot Nhất Sài Gòn & US",
        description: "Bột tráng gương ánh bạc sắc lạnh phản quang 360 độ, form móng nhọn nổi loạn chuẩn vibe phố đi bộ.",
        recipe: "Base đen đậm + Chà bột tráng gương bạc Mirror Chrome mịn + Top cứng bảo vệ tráng gương"
    },
    {
        id: "gold-mirror-luxury",
        name: "Tráng Gương Hoàng Kim 24K",
        category: "y2k",
        categoryName: "⚡ Y2K & Cháy Phố (Sài Gòn & USA)",
        shape: "coffin",
        length: 1.45,
        finish: "chrome",
        primaryColor: "#E5C07B",
        secondaryColor: "#B8860B",
        frenchTip: false,
        gemstones: true,
        glitter: false,
        catEye: false,
        tag: "Tài Lộc Rực Rỡ",
        description: "Bột tráng gương vàng kim loại lấp lánh như dát vàng nguyên khối, khẳng định đẳng cấp sang giàu.",
        recipe: "Chà bột Chrome Gold ánh kim loại + Top bóng không chảy láng mịn"
    },
    {
        id: "y2k-black-pink",
        name: "Hồng Đen Punk Rock Y2K",
        category: "y2k",
        categoryName: "⚡ Y2K & Cháy Phố (Sài Gòn & USA)",
        shape: "coffin",
        length: 1.4,
        finish: "matte",
        primaryColor: "#18181B",
        secondaryColor: "#FF2A85",
        frenchTip: true,
        frenchColor: "#FF2A85",
        gemstones: true,
        glitter: false,
        catEye: false,
        tag: "Cá Tính Nổi Loạn",
        description: "Phối hợp đen nhám quyền lực và viền hồng cánh sen dạ quang, kèm charm chữ thập gothic.",
        recipe: "Sơn đen lì velvet + Vẽ line viền hồng neon dạ quang + Đính charm kim loại chrome"
    },
    {
        id: "french-classic-pearl",
        name: "French Cổ Điển Tinh Tế",
        category: "classic",
        categoryName: "✨ Kinh Điển & Thanh Lịch",
        shape: "almond",
        length: 1.2,
        finish: "glossy",
        primaryColor: "#FFF0F5",
        secondaryColor: "#FFFFFF",
        frenchTip: true,
        frenchColor: "#FFFFFF",
        gemstones: false,
        glitter: false,
        catEye: false,
        tag: "Mọi Thời Đại",
        description: "Nền móng hồng nude tự nhiên điểm đầu móng trắng tinh khôi chuẩn quý cô Paris kiêu sa.",
        recipe: "Sơn lót Nude Sheer 2 lớp + Kẻ line đầu móng nụ cười Smile Line trắng tuyết"
    },
    {
        id: "amber-latte-fall",
        name: "Hổ Phách Cà Phê Mùa Thu",
        category: "classic",
        categoryName: "✨ Kinh Điển & Thanh Lịch",
        shape: "round",
        length: 1.2,
        finish: "jelly",
        primaryColor: "#9C4221",
        secondaryColor: "#F3C99F",
        frenchTip: false,
        gemstones: false,
        glitter: true,
        catEye: false,
        goldFoil: true,
        tag: "Mùa Thu Thơ Mộng",
        description: "Vân đá hổ phách mật ong loang cùng tone trà sữa caramen, ấm áp và lãng mạn.",
        recipe: "Loang thạch nâu hổ phách + Viền nhũ vàng sâm panh nhẹ nhàng"
    }
];

// Danh sách màu sắc Salon kinh điển cho bộ Custom Picker
const SALON_COLOR_PALETTES = [
    { name: "Hồng Thạch Douyin", hex: "#FF8DA1", type: "jelly" },
    { name: "Đỏ Rượu Bordeaux", hex: "#6B0D1B", type: "glossy" },
    { name: "Tráng Gương Bạc", hex: "#D1D5DB", type: "chrome" },
    { name: "Cẩm Thạch Lục Bảo", hex: "#0D5C3A", type: "glossy" },
    { name: "Mắt Mèo Đêm Huyền", hex: "#1F2937", type: "cat_eye" },
    { name: "Trắng Sữa Ngọc Trai", hex: "#FFFDF9", type: "glossy" },
    { name: "Cam Đào Mọng Nước", hex: "#FF8C5A", type: "jelly" },
    { name: "Hồng Nude Tự Nhiên", hex: "#F3D5CF", type: "jelly" },
    { name: "Vàng Kim 24K", hex: "#D4AF37", type: "chrome" },
    { name: "Xanh Baby Pastel", hex: "#93C5FD", type: "jelly" },
    { name: "Tím Oải Hương", hex: "#C4B5FD", type: "jelly" },
    { name: "Nâu Trà Sữa Latte", hex: "#A77B5A", type: "glossy" },
    { name: "Đỏ Cherry Tươi", hex: "#C8102E", type: "glossy" },
    { name: "Đen Nhám Gothic", hex: "#18181B", type: "matte" },
    { name: "Hồng Neon Y2K", hex: "#FF1493", type: "chrome" },
    { name: "Xanh Coban Hoàng Gia", hex: "#1E3A8A", type: "glossy" },
    { name: "Hổ Phách Mật Ong", hex: "#B45309", type: "jelly" },
    { name: "Bạc Ánh Nhũ Hologram", hex: "#E0E7FF", type: "chrome" }
];
